// src/quizData.jsx

export const baseRecommendations = {
  "Digital, Information & Tech Professionals": "The Chartered Institute for IT",
  "Clinical Informatics Professionals": "The Chartered Institute for IT",
  "Analysts, Data & Analytics Professionals": "The Association of Professional Healthcare Analysts",
  "Information & Records Management, Clinical Coding, etc.": "The Institute of Health Records & Information Management",
  "Information Professionals, Knowledge Managers, etc.": "The Library and Information Association",
  "Leaders in Digital Healthcare": "The College of Healthcare Information Management Executives"
};

export const familyToBodyMapping = {
  "Architecture": "The Chartered Institute for IT",
  "Data": "The Association of Professional Healthcare Analysts",
  "IT Operations": "The Chartered Institute for IT",
  "Product and Delivery": "The Chartered Institute for IT",
  "Software Development": "The Chartered Institute for IT",
  "Quality Assurance Testing": "The Chartered Institute for IT",
  "User Centred Design": "The Chartered Institute for IT",
  "Patient Services": "The Institute of Health Records & Information Management",
  "Information Governance": "The Institute of Health Records & Information Management",
  "Cyber Security": "The Chartered Institute for IT",
  "Clinical Informatics": "The Chartered Institute for IT",
  "Digital Leadership Roles": "The College of Healthcare Information Management Executives",
  "Knowledge Management": "The Library and Information Association"
};

export const roleToBodyMapping = {
  // BCS or CHIME
  "CXIO": [
    "The Chartered Institute for IT",
    "The College of Healthcare Information Management Executives",
  ],
  "Chief Information Officer": [
    "The Chartered Institute for IT",
    "The College of Healthcare Information Management Executives",
  ],
  "Chief Digital Information Officer": [
    "The Chartered Institute for IT",
    "The College of Healthcare Information Management Executives",
  ],
  "Chief Information Security Officer": [
    "The Chartered Institute for IT",
    "The College of Healthcare Information Management Executives",
  ],
  "Chief Technology Officer": [
    "The Chartered Institute for IT",
    "The College of Healthcare Information Management Executives",
  ],
  "Chief Audit Officer": [
    "The Chartered Institute for IT",
    "The College of Healthcare Information Management Executives",
  ],

  // AphA
  "Chief Data Officer": "The Association of Professional Healthcare Analysts",
  "Chief Analytical Officer": "The Association of Professional Healthcare Analysts",
};


export const jobFamilies = {
  "Architecture": {
    "Business Architecture": ["Lead Business Architect", "Associate Business Architect", "Trainee Business Architect", "Business Architect"],
    "Data Architecture": ["Chief Data Architect", "Data Architect", "Senior Data Architect"],
    "Enterprise Architecture": ["Principal Enterprise Architect", "Lead Enterprise Architect", "Enterprise Architect", "Senior Enterprise Architect"],
    "Network Architecture": ["Lead Network Architect", "Associate Network Architect", "Network Architect"],
    "Security Architecture": ["Lead Security Architect", "Security Architect", "Principal Security Architect"],
    "Solution Architecture": ["Associate Solution Architect", "Principal Solution Architect", "Senior Solution Architect", "Solution Architect", "Lead Solution Architect"],
    "Technical Architecture": ["Lead Technical Architect", "Associate Technical Architect", "Principal Technical Architect", "Senior Technical Architect", "Technical Architect"]
  },
  "Clinical Informatics": {
    "Clinical Informatics": ["Clinical Informatician", "Senior Clinical Informatician"]
  },
  "Cyber Security": {
    "Cyber Security": ["Cyber Security Analyst", "Senior Cyber Security Analyst"],
    "Cyber Security Management": ["Assistant Director of Cyber Security (Governance, Risk and Compliance)", "Assistant Director of Cyber Security (Operations)", "Cyber Security Manager (Governance, Risk and Compliance)", "Cyber Security Manager (Operations)", "Cyber Security Specialist (Governance, Risk and Compliance)", "Cyber Security Specialist (Operations)", "Head of Cyber Security (Governance, Risk and Compliance)", "Head of Cyber Security (Operations)"]
  },
  "Data": {
    "Data Analysis": ["Lead Data Analyst", "Principal Data Analyst", "Senior Data Analyst", "Data Analyst", "Associate Data Analyst"],
    "Data Engineering": ["Head of Analytics Engineering", "Lead Analytics Engineer", "Principal Data Engineer", "Senior Analytics Engineer", "Senior Data Engineer", "Analytics Engineer", "Data Engineer", "Associate Data Engineer"],
    "Data Governance": ["Lead Data Governance Manager", "Senior Data Governance Manager", "Data Governance Manager"],
    "Data Science": ["Lead Data Scientist", "Lead Machine Learning Engineer", "Principal Data Scientist", "Senior Data Scientist", "Senior Machine Learning Engineer", "Data Scientist"],
    "Data ethics": ["Data Ethics Lead", "Head of Data Ethics"]
  },
"Digital Leadership Roles": {
  "Digital Leadership Roles": [
    "Chief Technology Officer",
    "Chief Audit Officer",
    "Chief Information Officer",
    "Chief Digital Information Officer",
    "Chief Data Officer",
    "Chief Information Security Officer",
    "Chief Analytical Officer",
    "CXIO",
  ],
},

  "IT Operations": {
    "Application Operations": ["Application Operations Engineer", "Associate Application Operations Engineer", "Lead Application Operations Engineer", "Principal Application Operations Engineer", "Senior Application Operations Engineer"],
    "Business Relationship Management": ["Business Relationship Manager", "Lead Business Relationship Manager", "Senior Business Relationship Manager"],
    "End User Computing": ["Associate End User Computing Engineer", "End User Computing Engineer", "Lead End User Computing Engineer", "Principal End User Computing Engineer", "Senior End User Computing Engineer"],
    "Infrastructure Operations": ["Associate Infrastructure Engineer", "Associate Infrastructure Operations Engineer", "Infrastructure Engineer", "Infrastructure Operations Engineer", "Lead Infrastructure Engineer", "Lead Infrastructure Operations Engineer", "Principal Infrastructure Engineer", "Principal Infrastructure Operations Engineer", "Senior Infrastructure Engineer", "Senior Infrastructure Operations Engineer"],
    "IT Service Management": ["Change and Release Analyst", "Change and Release Manager", "Configuration Analyst", "Head of Command and Control", "Head of IT Service Management", "Head of Service Desk", "Incident Manager", "IT Service Analyst", "IT Service Manager", "Lead Service Transition Manager", "Major Incident Manager", "Operational Control Manager", "Operations Analyst", "Problem Analyst", "Problem Manager", "Senior IT Service Manager", "Senior Operations Analyst", "Senior Service Desk Analyst", "Service Acceptance Analyst", "Service Desk Analyst", "Service Desk Manager", "Service Readiness Analyst", "Service Transition Manager"]
  },
  "Information Governance": {
    "Information Governance Officers": ["Senior Information Governance Officer", "Information Governance Administrator", "Information Governance Officer"],
    "Information Governance Managers": ["Information Governance Manager", "Head of Information Governance"],
    "Data Protection Officer": ["Data Protection Officer"]
  },
  "Patient Services": {
    "Clinical Coding": ["Clinical Coding Manager", "Trainee Clinical Coder", "Head of Clinical Coding", "Qualified Clinical Coder", "Clinical Coding Auditor", "Clinical Coding Team Leader", "Clinical Coding Trainer"],
    "Records and Information Manager": ["Records and Information Manager", "Digital Clerk", "Records and Information Team Leader/Supervisor", "Assistant Records and Information Manager"]
  },
  "Product and Delivery": {
    "Business Analysis": ["Head of Business Analysis", "Lead Business Analyst", "Senior Business Analyst", "Business Analyst", "Junior Business Analyst", "Trainee Business Analyst"],
    "Delivery Management": ["Head of (Agile) Delivery Management", "Programme Delivery Manager", "Senior Delivery Manager", "Delivery Manager", "Associate Delivery Manager"],
    "Portfolio Management": ["Head of Portfolio", "Senior Digital Portfolio Manager", "Digital Portfolio Analyst", "Digital Portfolio Manager"],
    "Product Management": ["Head of Product", "Lead Product Manager", "Senior Product Manager", "Product Manager", "Associate Product Manager", "Service Owner"]
  },
  "Quality Assurance Testing": {
    "Quality Assurance Testing (QAT) Analyst": ["Lead QAT Analyst", "QAT Tester", "QAT Analyst", "Senior QAT Analyst"],
    "Test Engineer": ["Lead Test Engineer", "Tester (Test Engineer)", "Test Engineer", "Senior Test Engineer"],
    "Test Manager": ["Test Manager", "Head of Test"]
  },
  "Software Development": {
    "Developer roles": ["Developer", "Frontend Developer", "Head of Frontend Development", "Junior Developer", "Junior Frontend Developer", "Lead Developer", "Lead Developer - Management", "Lead Frontend Developer", "Principal Developer", "Principal Developer - Management", "Senior Developer", "Senior Developer - Management", "Senior Frontend Developer", "Apprentice Developer", "Apprentice Frontend Developer"],
    "DevOps": ["Apprentice DevOps Engineer", "DevOps Engineer", "Junior DevOps Engineer", "Lead DevOps Engineer", "Lead DevOps Engineer - Management", "Principal DevOps Engineer", "Principal DevOps engineer - Management", "Senior DevOps Engineer", "Senior DevOps Engineer - Management"]
  },
  "User Centred Design": {
    "Accessibility": ["Head of Accessibility", "Senior Accessibility Specialist", "Accessibility Specialist", "Junior Accessibility Specialist"],
    "Content Design": ["Head of Content Design", "Lead Content Designer", "Senior Content Designer", "Content Designer", "Associate Content Designer", "Junior Content Designer"],
    "Content Strategist": ["Content Strategist"],
    "Graphic Design": ["Head of Graphic Design", "Lead Graphic Designer", "Senior Graphic Designer", "Graphic Designer", "Associate Graphic Designer", "Junior Graphic Designer"],
    "Interaction Design": ["Head of Interaction Design", "Lead Interaction Designer", "Senior Interaction Designer", "Interaction Designer", "Associate Interaction Designer", "Junior Interaction Designer"],
    "Service Design": ["Head of Service Design", "Lead Service Designer", "Senior Service Designer", "Service Designer", "Associate Service Designer", "Junior Service Designer"],
    "Technical Writing": ["Lead Technical Writer", "Technical Writer"],
    "User Research": ["Head of User Research", "Lead User Researcher", "Senior User Researcher", "User Researcher", "Associate User Researcher", "Junior User Researcher"]
  }
};

export const detailedFedipMapping = {
    "Accessibility Specialist": "FEDIP Practitioner",
  "Associate Content Designer": "FEDIP Associate Practitioner",
  "Associate Graphic Designer": "FEDIP Associate Practitioner",
  "Associate Interaction Designer": "FEDIP Associate Practitioner",
  "Associate Service Designer": "FEDIP Associate Practitioner",
  "Associate User Researcher": "FEDIP Associate Practitioner",
  "Content Designer": "FEDIP Practitioner",
  "Data Ethics Lead": "FEDIP Advanced Practitioner",
  "Graphic Designer": "FEDIP Practitioner",
  "Head of Accessibility": "FEDIP Leading Practitioner",
  "Interaction Designer": "FEDIP Practitioner",
  "Junior Accessibility Specialist": "FEDIP Associate Practitioner",
  "Junior Content Designer": "FEDIP Associate Practitioner",
  "Junior Graphic Designer": "FEDIP Associate Practitioner",
  "Junior Interaction Designer": "FEDIP Associate Practitioner",
  "Junior Service Designer": "FEDIP Associate Practitioner",
  "Junior User Researcher": "FEDIP Associate Practitioner",
  "Lead Analytics Engineer": "FEDIP Advanced Practitioner",
  "Lead Infrastructure Operations Engineer": "FEDIP Advanced Practitioner",
  "Principal Data Analyst": "FEDIP Leading Practitioner",
  "Principal Data Engineer": "FEDIP Leading Practitioner",
  "Principal Data Scientist": "FEDIP Leading Practitioner",
  "Senior Accessibility Specialist": "FEDIP Senior Practitioner",
  "Senior Analytics Engineer": "FEDIP Senior Practitioner",
  "Senior Content Designer": "FEDIP Senior Practitioner",
  "Senior Frontend Developer": "FEDIP Senior Practitioner",
  "Senior Graphic Designer": "FEDIP Senior Practitioner",
  "Senior Interaction Designer": "FEDIP Senior Practitioner",
  "Senior Service Designer": "FEDIP Senior Practitioner",
  "Senior User Researcher": "FEDIP Senior Practitioner",
  "Service Designer": "FEDIP Practitioner",
  "User Researcher": "FEDIP Practitioner",
  "Senior Information Governance Officer": "FEDIP Senior Practitioner",
  "Clinical Coding Manager": "FEDIP Advanced Practitioner",
  "Content Strategist": "FEDIP Advanced Practitioner",
  "Assistant Director of Cyber Security (Governance, Risk and Compliance)": "FEDIP Leading Practitioner",
  "Assistant Director of Cyber Security (Operations)": "FEDIP Leading Practitioner",
  "Delivery Manager": "FEDIP Practitioner",
  "Associate Solution Architect": "FEDIP Practitioner",
  "Head of (Agile) Delivery Management": "FEDIP Leading Practitioner",
  "Head of Analytics Engineering": "FEDIP Leading Practitioner",
  "Head of Business Analysis": "FEDIP Leading Practitioner",
  "Head of Clinical Coding": "FEDIP Leading Practitioner",
  "Head of Content Design": "FEDIP Leading Practitioner",
  "Head of Cyber Security (Governance, Risk and Compliance)": "FEDIP Leading Practitioner",
  "Head of Cyber Security (Operations)": "FEDIP Leading Practitioner",
  "Head of Data Ethics": "FEDIP Leading Practitioner",
  "Head of Frontend Development": "FEDIP Leading Practitioner",
  "Head of Graphic Design": "FEDIP Leading Practitioner",
  "Head of Interaction Design": "FEDIP Leading Practitioner",
  "Head of Portfolio": "FEDIP Leading Practitioner",
  "Head of Product": "FEDIP Leading Practitioner",
  "Head of Service Design": "FEDIP Leading Practitioner",
  "Head of Test": "FEDIP Leading Practitioner",
  "Head of User Research": "FEDIP Leading Practitioner",
  "Lead Business Analyst": "FEDIP Advanced Practitioner",
  "Lead Business Architect": "FEDIP Advanced Practitioner",
  "Lead Content Designer": "FEDIP Advanced Practitioner",
  "Lead Data Analyst": "FEDIP Advanced Practitioner",
  "Lead Data Engineer": "FEDIP Advanced Practitioner",
  "Lead Data Governance Manager": "FEDIP Advanced Practitioner",
  "Lead Data Scientist": "FEDIP Advanced Practitioner",
  "Lead Developer": "FEDIP Advanced Practitioner",
  "Lead Developer - Management": "FEDIP Advanced Practitioner",
  "Lead DevOps Engineer": "FEDIP Advanced Practitioner",
  "Lead DevOps Engineer - Management": "FEDIP Advanced Practitioner",
  "Lead Frontend Developer": "FEDIP Advanced Practitioner",
  "Lead Graphic Designer": "FEDIP Advanced Practitioner",
  "Lead Infrastructure Engineer": "FEDIP Advanced Practitioner",
  "Lead Interaction Designer": "FEDIP Advanced Practitioner",
  "Lead Machine Learning Engineer": "FEDIP Advanced Practitioner",
  "Lead Network Architect": "FEDIP Advanced Practitioner",
  "Lead Product Manager": "FEDIP Advanced Practitioner",
  "Lead QAT Analyst": "FEDIP Advanced Practitioner",
  "Lead Security Architect": "FEDIP Advanced Practitioner",
  "Lead Service Designer": "FEDIP Advanced Practitioner",
  "Lead Technical Architect": "FEDIP Advanced Practitioner",
  "Lead Technical Writer": "FEDIP Leading Practitioner",
  "Lead Test Engineer": "FEDIP Advanced Practitioner",
  "Lead User Researcher": "FEDIP Advanced Practitioner",
  "Product Manager": "FEDIP Practitioner",
  "Programme Delivery Manager": "FEDIP Advanced Practitioner",
  "Security Architect": "FEDIP Practitioner",
  "Senior Business Analyst": "FEDIP Senior Practitioner",
  "Senior Delivery Manager": "FEDIP Senior Practitioner",
  "Senior Product Manager": "FEDIP Senior Practitioner",
  "Senior Digital Portfolio Manager": "FEDIP Senior Practitioner",
  "Test Manager": "FEDIP Advanced Practitioner",
  "Analytics Engineer": "FEDIP Practitioner",
  "Application Operations Engineer": "FEDIP Practitioner",
  "Associate Application Operations Engineer": "FEDIP Associate Practitioner",
  "Associate Business Architect": "FEDIP Practitioner",
  "Business Architect": "FEDIP Senior Practitioner",
  "Associate End User Computing Engineer": "FEDIP Associate Practitioner",
  "Associate Infrastructure Engineer": "FEDIP Associate Practitioner",
  "Associate Infrastructure Operations Engineer": "FEDIP Associate Practitioner",
  "Associate Network Architect": "FEDIP Practitioner",
  "Associate Technical Architect": "FEDIP Practitioner",
  "Business Relationship Manager": "FEDIP Practitioner",
  "Change and Release Analyst": "FEDIP Senior Practitioner",
  "Change and Release Manager": "FEDIP Practitioner",
  "End User Computing Engineer": "FEDIP Practitioner",
  "Head of Command and Control": "FEDIP Leading Practitioner",
  "Head of IT Service Management": "FEDIP Leading Practitioner",
  "Head of Service Desk": "FEDIP Leading Practitioner",
  "Incident Manager": "FEDIP Practitioner",
  "Infrastructure Engineer": "FEDIP Practitioner",
  "Infrastructure Operations Engineer": "FEDIP Practitioner",
  "IT Service Analyst": "FEDIP Practitioner",
  "Lead Application Operations Engineer": "FEDIP Advanced Practitioner",
  "Lead Business Relationship Manager": "FEDIP Advanced Practitioner",
  "Lead End User Computing Engineer": "FEDIP Advanced Practitioner",
  "Lead Service Transition Manager": "FEDIP Advanced Practitioner",
  "Major Incident Manager": "FEDIP Advanced Practitioner",
  "Operational Control Manager": "FEDIP Practitioner",
  "Operations Analyst": "FEDIP Associate Practitioner",
  "Principal Application Operations Engineer": "FEDIP Leading Practitioner",
  "Principal End User Computing Engineer": "FEDIP Leading Practitioner",
  "Principal Infrastructure Engineer": "FEDIP Leading Practitioner",
  "Principal Infrastructure Operations Engineer": "FEDIP Leading Practitioner",
  "Principal Technical Architect": "FEDIP Leading Practitioner",
  "Problem Analyst": "FEDIP Practitioner",
  "Problem Manager": "FEDIP Advanced Practitioner",
  "Senior Application Operations Engineer": "FEDIP Senior Practitioner",
  "Senior Business Relationship Manager": "FEDIP Senior Practitioner",
  "Trainee Business Architect": "FEDIP Associate Practitioner",
  "Principal Enterprise Architect": "FEDIP Leading Practitioner",
  "Assistant Records and Information Manager": "FEDIP Senior Practitioner",
  "Clinical Coding Auditor": "FEDIP Senior Practitioner",
  "Clinical Coding Team Leader": "FEDIP Senior Practitioner",
  "Clinical Coding Trainer": "FEDIP Senior Practitioner",
  "Digital Clerk": "FEDIP Associate Practitioner",
  "Qualified Clinical Coder": "FEDIP Practitioner",
  "Records and Information Manager": "FEDIP Advanced Practitioner",
  "Records and Information Team Leader/Supervisor": "FEDIP Practitioner",
  "Trainee Clinical Coder": "FEDIP Associate Practitioner",
  "Chief Technology Officer": "FEDIP Leading Practitioner",
  "Chief Audit Officer": "FEDIP Leading Practitioner",
  "Chief Data Architect": "FEDIP Leading Practitioner",
  "Chief Information Officer": "FEDIP Leading Practitioner",
  "Clinical Informatician": "FEDIP Practitioner",
  "CXIO": "FEDIP Leading Practitioner",
  "Lead Enterprise Architect": "FEDIP Advanced Practitioner",
  "Principal Security Architect": "FEDIP Leading Practitioner",
  "Principal Solution Architect": "FEDIP Leading Practitioner",
  "Senior Clinical Informatician": "FEDIP Senior Practitioner",
  "Apprentice DevOps Engineer": "FEDIP Associate Practitioner",
  "Associate Delivery Manager": "FEDIP Associate Practitioner",
  "Associate Product Manager": "FEDIP Associate Practitioner",
  "Business Analyst": "FEDIP Practitioner",
  "Data Architect": "FEDIP Practitioner",
  "Developer": "FEDIP Practitioner",
  "DevOps Engineer": "FEDIP Practitioner",
  "Enterprise Architect": "FEDIP Practitioner",
  "Frontend Developer": "FEDIP Practitioner",
  "IT Service Manager": "FEDIP Senior Practitioner",
  "Junior Business Analyst": "FEDIP Associate Practitioner",
  "Junior Developer": "FEDIP Associate Practitioner",
  "Junior DevOps Engineer": "FEDIP Associate Practitioner",
  "Junior Frontend Developer": "FEDIP Associate Practitioner",
  "Network Architect": "FEDIP Practitioner",
  "Service Owner": "FEDIP Advanced Practitioner",
  "Solution Architect": "FEDIP Practitioner",
  "Technical Architect": "FEDIP Practitioner",
  "Trainee Business Analyst": "FEDIP Associate Practitioner",
  "Configuration Analyst": "None",
  "Cyber Security Analyst": "FEDIP Associate Practitioner",
  "Data Analyst": "FEDIP Practitioner",
  "Data Engineer": "FEDIP Practitioner",
  "Data Governance Manager": "FEDIP Practitioner",
  "Data Scientist": "FEDIP Practitioner",
  "Head of Information Governance": "FEDIP Leading Practitioner",
  "Information Governance Administrator": "FEDIP Associate Practitioner",
  "Information Governance Manager": "FEDIP Advanced Practitioner",
  "Information Governance Officer": "FEDIP Practitioner",
  "Principal Developer": "FEDIP Leading Practitioner",
  "Principal Developer - Management": "FEDIP Leading Practitioner",
  "Principal DevOps Engineer": "FEDIP Leading Practitioner",
  "Principal DevOps engineer - Management": "FEDIP Leading Practitioner",
  "Senior Data Analyst": "FEDIP Senior Practitioner",
  "Senior Data Engineer": "FEDIP Senior Practitioner",
  "Senior Data Governance Manager": "FEDIP Senior Practitioner",
  "Senior Data Scientist": "FEDIP Senior Practitioner",
  "Senior Developer": "FEDIP Senior Practitioner",
  "Senior Developer - Management": "FEDIP Senior Practitioner",
  "Senior DevOps Engineer": "FEDIP Senior Practitioner",
  "Senior DevOps Engineer - Management": "FEDIP Senior Practitioner",
  "Senior Enterprise Architect": "FEDIP Senior Practitioner",
  "Senior IT Service Manager": "FEDIP Senior Practitioner",
  "Senior Solution Architect": "FEDIP Senior Practitioner",
  "Senior Technical Architect": "FEDIP Senior Practitioner",
  "Service Acceptance Analyst": "FEDIP Associate Practitioner",
  "Service Desk Analyst": "FEDIP Associate Practitioner",
  "Service Readiness Analyst": "FEDIP Practitioner",
  "Apprentice Developer": "FEDIP Associate Practitioner",
  "Apprentice Frontend Developer": "FEDIP Associate Practitioner",
  "Associate Data Analyst": "FEDIP Associate Practitioner",
  "Associate Data Engineer": "FEDIP Associate Practitioner",
  "QAT Analyst": "FEDIP Practitioner",
  "QAT Tester": "FEDIP Associate Practitioner",
  "Senior QAT Analyst": "FEDIP Senior Practitioner",
  "Senior Test Engineer": "FEDIP Senior Practitioner",
  "Test Engineer": "FEDIP Practitioner",
  "Tester (Test Engineer)": "FEDIP Associate Practitioner",
  "Senior Data Architect": "FEDIP Senior Practitioner",
  "Cyber Security Manager (Governance, Risk and Compliance)": "FEDIP Advanced Practitioner",
  "Cyber Security Manager (Operations)": "FEDIP Advanced Practitioner",
  "Cyber Security Specialist (Governance, Risk and Compliance)": "FEDIP Senior Practitioner",
  "Cyber Security Specialist (Operations)": "FEDIP Senior Practitioner",
  "Senior Cyber Security Analyst": "FEDIP Senior Practitioner",
  "Senior End User Computing Engineer": "FEDIP Senior Practitioner",
  "Senior Infrastructure Engineer": "FEDIP Senior Practitioner",
  "Senior Infrastructure Operations Engineer": "FEDIP Senior Practitioner",
  "Senior Machine Learning Engineer": "FEDIP Senior Practitioner",
  "Senior Operations Analyst": "FEDIP Senior Practitioner",
  "Senior Service Desk Analyst": "FEDIP Senior Practitioner",
  "Service Desk Manager": "FEDIP Senior Practitioner",
  "Service Transition Manager": "FEDIP Senior Practitioner",
  "Technical Writer": "FEDIP Senior Practitioner",
  "Data Protection Officer": "FEDIP Leading Practitioner",
  "Digital Portfolio Analyst": "FEDIP Practitioner",
  "Digital Portfolio Manager": "FEDIP Practitioner",
  "Chief Digital Information Officer": "FEDIP Leading Practitioner",
"Chief Data Officer": "FEDIP Leading Practitioner",
"Chief Information Security Officer": "FEDIP Leading Practitioner",
"Chief Analytical Officer": "FEDIP Leading Practitioner",
  "Lead Solution Architect": "FEDIP Leading Practitioner"
};

export const subFamilyToBodyMapping = {
  "Data Architecture": "The Association of Professional Healthcare Analysts"
};