// src/quizData.jsx

export const baseRecommendations = {
  "User Centred Design": "BCS, The Chartered Institute for IT",
  "Architecture": "BCS, The Chartered Institute for IT",
  "Data": "Association of Professional Healthcare Analysts (AphA)",
  "IT Operations": "BCS, The Chartered Institute for IT",
  "Product and Delivery": "BCS, The Chartered Institute for IT",
  "Software Development": "BCS, The Chartered Institute for IT",
  "Cyber Security": "BCS, The Chartered Institute for IT",
  "Clinical Informatics": "CHIME",
  "Information Governance": "Institute of Health Records and Information Management (IHRIM)",
  "Knowledge Management": "CILIP, The Library and Information Association",
  "Patient Services": "Institute of Health Records and Information Management (IHRIM)",
  "Quality Assurance Testing": "BCS, The Chartered Institute for IT",
  "Digital Leadership Roles": "CHIME"
};

export const jobFamilies = {
  "Architecture": ["Associate Business Architect", "Associate Network Architect", "Associate Solution Architect", "Associate Technical Architect", "Business Architect", "Chief Data Architect", "Data Architect", "Enterprise Architect", "Lead Business Architect", "Lead Enterprise Architect", "Lead Network Architect", "Lead Security Architect", "Lead Solution Architect", "Lead Technical Architect", "Network Architect", "Principal Enterprise Architect", "Principal Security Architect", "Principal Solution Architect", "Principal Technical Architect", "Security Architect", "Senior Data Architect", "Senior Enterprise Architect", "Senior Solution Architect", "Senior Technical Architect", "Solution Architect", "Technical Architect", "Trainee Business Architect"],
  "Clinical Informatics": ["Clinical Informatician", "Senior Clinical Informatician"],
  "Cyber Security": ["Assistant Director of Cyber Security (Governance, Risk and Compliance)", "Assistant Director of Cyber Security (Operations)", "Cyber Security Analyst", "Cyber Security Manager (Governance, Risk and Compliance)", "Cyber Security Manager (Operations)", "Cyber Security Specialist (Governance, Risk and Compliance)", "Cyber Security Specialist (Operations)", "Head of Cyber Security (Governance, Risk and Compliance)", "Head of Cyber Security (Operations)", "Senior Cyber Security Analyst"],
  "Data": ["Analytics Engineer", "Associate Data Analyst", "Associate Data Engineer", "Data Analyst", "Data Engineer", "Data Ethics Lead", "Data Governance Manager", "Data Scientist", "Head of Analytics Engineering", "Head of Data Ethics", "Lead Analytics Engineer", "Lead Data Analyst", "Lead Data Engineer", "Lead Data Governance Manager", "Lead Data Scientist", "Lead Machine Learning Engineer", "Principal Data Analyst", "Principal Data Engineer", "Principal Data Scientist", "Senior Analytics Engineer", "Senior Data Analyst", "Senior Data Engineer", "Senior Data Governance Manager", "Senior Data Scientist", "Senior Machine Learning Engineer"],
  "Digital Leadership Roles": ["Chief Audit Officer", "Chief Information Officer", "Chief Technology Officer", "CXIO"],
  "IT Operations": ["Application Operations Engineer", "Associate Application Operations Engineer", "Associate End User Computing Engineer", "Associate Infrastructure Engineer", "Associate Infrastructure Operations Engineer", "Business Relationship Manager", "Change and Release Analyst", "Change and Release Manager", "Configuration Analyst", "End User Computing Engineer", "Head of Command and Control", "Head of IT Service Management", "Head of Service Desk", "Incident Manager", "Infrastructure Engineer", "Infrastructure Operations Engineer", "IT Service Analyst", "IT Service Manager", "Lead Application Operations Engineer", "Lead Business Relationship Manager", "Lead End User Computing Engineer", "Lead Infrastructure Engineer", "Lead Infrastructure Operations Engineer", "Lead Service Transition Manager", "Major Incident Manager", "Operational Control Manager", "Operations Analyst", "Principal Application Operations Engineer", "Principal End User Computing Engineer", "Principal Infrastructure Engineer", "Principal Infrastructure Operations Engineer", "Problem Analyst", "Problem Manager", "Senior Application Operations Engineer", "Senior Business Relationship Manager", "Senior End User Computing Engineer", "Senior Infrastructure Engineer", "Senior Infrastructure Operations Engineer", "Senior IT Service Manager", "Senior Operations Analyst", "Senior Service Desk Analyst", "Service Acceptance Analyst", "Service Desk Analyst", "Service Desk Manager", "Service Readiness Analyst", "Service Transition Manager"],
  "Information Governance": ["Data Protection Officer", "Head of Information Governance", "Information Governance Administrator", "Information Governance Manager", "Information Governance Officer", "Senior Information Governance Officer"],
  "Patient Services": ["Assistant Records and Information Manager", "Clinical Coding Auditor", "Clinical Coding Manager", "Clinical Coding Team Leader", "Clinical Coding Trainer", "Digital Clerk", "Head of Clinical Coding", "Qualified Clinical Coder", "Records and Information Manager", "Records and Information Team Leader/Supervisor", "Trainee Clinical Coder"],
  "Product and Delivery": ["Associate Delivery Manager", "Associate Product Manager", "Business Analyst", "Delivery Manager", "Digital Portfolio Analyst", "Digital Portfolio Manager", "Head of (Agile) Delivery Management", "Head of Business Analysis", "Head of Portfolio", "Head of Product", "Junior Business Analyst", "Lead Business Analyst", "Lead Product Manager", "Product Manager", "Programme Delivery Manager", "Senior Business Analyst", "Senior Delivery Manager", "Senior Digital Portfolio Manager", "Senior Product Manager", "Service Owner", "Trainee Business Analyst"],
  "Quality Assurance Testing": ["Head of Test", "Lead QAT Analyst", "Lead Test Engineer", "QAT Analyst", "QAT Tester", "Senior QAT Analyst", "Senior Test Engineer", "Test Engineer", "Test Manager", "Tester (Test Engineer)"],
  "Software Development": ["Apprentice Developer", "Apprentice DevOps Engineer", "Apprentice Frontend Developer", "Developer", "DevOps Engineer", "Frontend Developer", "Head of Frontend Development", "Junior Developer", "Junior DevOps Engineer", "Junior Frontend Developer", "Lead Developer", "Lead Developer - Management", "Lead DevOps Engineer", "Lead DevOps Engineer - Management", "Lead Frontend Developer", "Principal Developer", "Principal Developer - Management", "Principal DevOps Engineer", "Principal DevOps engineer - Management", "Senior Developer", "Senior Developer - Management", "Senior DevOps Engineer", "Senior DevOps Engineer - Management", "Senior Frontend Developer"],
  "User Centred Design": ["Accessibility Specialist", "Associate Content Designer", "Associate Graphic Designer", "Associate Interaction Designer", "Associate Service Designer", "Associate User Researcher", "Content Designer", "Content Strategist", "Graphic Designer", "Head of Accessibility", "Head of Content Design", "Head of Graphic Design", "Head of Interaction Design", "Head of Service Design", "Head of User Research", "Interaction Designer", "Junior Accessibility Specialist", "Junior Content Designer", "Junior Graphic Designer", "Junior Interaction Designer", "Junior Service Designer", "Junior User Researcher", "Lead Content Designer", "Lead Graphic Designer", "Lead Interaction Designer", "Lead Service Designer", "Lead Technical Writer", "Lead User Researcher", "Senior Accessibility Specialist", "Senior Content Designer", "Senior Graphic Designer", "Senior Interaction Designer", "Senior Service Designer", "Senior User Researcher", "Service Designer", "Technical Writer", "User Researcher"]
};

export const detailedFedipMapping = {
  "Accessibility Specialist": "FEDIP Practitioner",
  "Analytics Engineer": "FEDIP Practitioner",
  "Apprentice Developer": "FEDIP Associate Practitioner",
  "Apprentice DevOps Engineer": "FEDIP Associate Practitioner",
  "Apprentice Frontend Developer": "FEDIP Associate Practitioner",
  "Assistant Director of Cyber Security (Governance, Risk and Compliance)": "FEDIP Leading Practitioner",
  "Assistant Director of Cyber Security (Operations)": "FEDIP Leading Practitioner",
  "Assistant Records and Information Manager": "FEDIP Senior Practitioner",
  "Associate Business Architect": "FEDIP Practitioner",
  "Associate Content Designer": "FEDIP Associate Practitioner",
  "Associate Data Analyst": "FEDIP Associate Practitioner",
  "Associate Data Engineer": "FEDIP Associate Practitioner",
  "Associate Delivery Manager": "FEDIP Associate Practitioner",
  "Associate Graphic Designer": "FEDIP Associate Practitioner",
  "Associate Infrastructure Engineer": "FEDIP Associate Practitioner",
  "Associate Interaction Designer": "FEDIP Associate Practitioner",
  "Associate Product Manager": "FEDIP Associate Practitioner",
  "Associate Service Designer": "FEDIP Associate Practitioner",
  "Associate User Researcher": "FEDIP Associate Practitioner",
  "Business Analyst": "FEDIP Practitioner",
  "Business Architect": "FEDIP Senior Practitioner",
  "Chief Data Architect": "FEDIP Leading Practitioner",
  "Chief Technology Officer": "FEDIP Leading Practitioner",
  "Clinical Coding Auditor": "FEDIP Senior Practitioner",
  "Clinical Coding Manager": "FEDIP Advanced Practitioner",
  "Clinical Coding Team Leader": "FEDIP Senior Practitioner",
  "Clinical Coding Trainer": "FEDIP Senior Practitioner",
  "Content Strategist": "FEDIP Advanced Practitioner",
  "Cyber Security Analyst": "FEDIP Associate Practitioner",
  "Cyber Security Manager (Governance, Risk and Compliance)": "FEDIP Advanced Practitioner",
  "Cyber Security Manager (Operations)": "FEDIP Advanced Practitioner",
  "Cyber Security Specialist (Governance, Risk and Compliance)": "FEDIP Senior Practitioner",
  "Cyber Security Specialist (Operations)": "FEDIP Senior Practitioner",
  "Data Analyst": "FEDIP Practitioner",
  "Data Engineer": "FEDIP Practitioner",
  "Data Ethics Lead": "FEDIP Advanced Practitioner",
  "Data Governance Manager": "FEDIP Practitioner",
  "Data Scientist": "FEDIP Practitioner",
  "Delivery Manager": "FEDIP Practitioner",
  "Developer": "FEDIP Practitioner",
  "DevOps Engineer": "FEDIP Practitioner",
  "Digital Clerk": "FEDIP Associate Practitioner",
  "Frontend Developer": "FEDIP Practitioner",
  "Graphic Designer": "FEDIP Practitioner",
  "Head of (Agile) Delivery Management": "FEDIP Leading Practitioner",
  "Head of Accessibility": "FEDIP Leading Practitioner",
  "Head of Analytics Engineering": "FEDIP Leading Practitioner",
  "Head of Business Analysis": "FEDIP Leading Practitioner",
  "Head of Clinical Coding": "FEDIP Leading Practitioner",
  "Head of Content Design": "FEDIP Leading Practitioner",
  "Head of Cyber Security (Governance, Risk and Compliance)": "FEDIP Leading Practitioner",
  "Head of Cyber Security (Operations)": "FEDIP Leading Practitioner",
  "Head of Data Ethics": "FEDIP Leading Practitioner",
  "Head of Frontend Development": "FEDIP Leading Practitioner",
  "Head of Graphic Design": "FEDIP Leading Practitioner",
  "Head of Interaction Design": "FEDIP Leading Practitioner",
  "Head of Product": "FEDIP Leading Practitioner",
  "Head of Service Design": "FEDIP Leading Practitioner",
  "Head of Test": "FEDIP Leading Practitioner",
  "Head of User Research": "FEDIP Leading Practitioner",
  "Infrastructure Engineer": "FEDIP Practitioner",
  "Interaction Designer": "FEDIP Practitioner",
  "Junior Accessibility Specialist": "FEDIP Associate Practitioner",
  "Junior Business Analyst": "FEDIP Associate Practitioner",
  "Junior Content Designer": "FEDIP Associate Practitioner",
  "Junior Developer": "FEDIP Associate Practitioner",
  "Junior DevOps Engineer": "FEDIP Associate Practitioner",
  "Junior Graphic Designer": "FEDIP Associate Practitioner",
  "Junior Interaction Designer": "FEDIP Associate Practitioner",
  "Junior Service Designer": "FEDIP Associate Practitioner",
  "Junior User Researcher": "FEDIP Associate Practitioner",
  "Lead Analytics Engineer": "FEDIP Advanced Practitioner",
  "Lead Business Analyst": "FEDIP Advanced Practitioner",
  "Lead Business Architect": "FEDIP Advanced Practitioner",
  "Lead Content Designer": "FEDIP Advanced Practitioner",
  "Lead Data Analyst": "FEDIP Advanced Practitioner",
  "Lead Data Engineer": "FEDIP Advanced Practitioner",
  "Lead Data Governance Manager": "FEDIP Advanced Practitioner",
  "Lead Data Scientist": "FEDIP Advanced Practitioner",
  "Lead Developer": "FEDIP Advanced Practitioner",
  "Lead Developer - Management": "FEDIP Advanced Practitioner",
  "Lead DevOps Engineer - Management": "FEDIP Advanced Practitioner",
  "Lead Frontend Developer": "FEDIP Advanced Practitioner",
  "Lead Graphic Designer": "FEDIP Advanced Practitioner",
  "Lead Infrastructure Engineer": "FEDIP Advanced Practitioner",
  "Lead Interaction Designer": "FEDIP Advanced Practitioner",
  "Lead Machine Learning Engineer": "FEDIP Advanced Practitioner",
  "Lead Product Manager": "FEDIP Advanced Practitioner",
  "Lead QAT Analyst": "FEDIP Advanced Practitioner",
  "Lead Service Designer": "FEDIP Advanced Practitioner",
  "Lead Technical Writer": "FEDIP Leading Practitioner",
  "Lead Test Engineer": "FEDIP Advanced Practitioner",
  "Lead User Researcher": "FEDIP Advanced Practitioner",
  "Principal Data Analyst": "FEDIP Leading Practitioner",
  "Principal Data Engineer": "FEDIP Leading Practitioner",
  "Principal Data Scientist": "FEDIP Leading Practitioner",
  "Principal Developer - Management": "FEDIP Leading Practitioner",
  "Principal DevOps Engineer": "FEDIP Leading Practitioner",
  "Principal DevOps engineer - Management": "FEDIP Leading Practitioner",
  "Principal Infrastructure Engineer": "FEDIP Leading Practitioner",
  "Product Manager": "FEDIP Practitioner",
  "Programme Delivery Manager": "FEDIP Advanced Practitioner",
  "QAT Analyst": "FEDIP Practitioner",
  "QAT Tester": "FEDIP Associate Practitioner",
  "Qualified Clinical Coder": "FEDIP Practitioner",
  "Records and Information Manager": "FEDIP Advanced Practitioner",
  "Records and Information Team Leader/Supervisor": "FEDIP Practitioner",
  "Senior Accessibility Specialist": "FEDIP Senior Practitioner",
  "Senior Analytics Engineer": "FEDIP Senior Practitioner",
  "Senior Business Analyst": "FEDIP Senior Practitioner",
  "Senior Data Analyst": "FEDIP Senior Practitioner",
  "Senior Data Engineer": "FEDIP Senior Practitioner",
  "Senior Data Governance Manager": "FEDIP Senior Practitioner",
  "Senior Data Scientist": "FEDIP Senior Practitioner",
  "Senior Delivery Manager": "FEDIP Senior Practitioner",
  "Senior Developer": "FEDIP Senior Practitioner",
  "Senior Developer - Management": "FEDIP Senior Practitioner",
  "Senior Graphic Designer": "FEDIP Senior Practitioner",
  "Senior Infrastructure Engineer": "FEDIP Senior Practitioner",
  "Senior Interaction Designer": "FEDIP Senior Practitioner",
  "Senior Machine Learning Engineer": "FEDIP Senior Practitioner",
  "Senior Product Manager": "FEDIP Senior Practitioner",
  "Senior QAT Analyst": "FEDIP Senior Practitioner",
  "Senior Service Designer": "FEDIP Senior Practitioner",
  "Senior Test Engineer": "FEDIP Senior Practitioner",
  "Senior User Researcher": "FEDIP Senior Practitioner",
  "Service Designer": "FEDIP Practitioner",
  "Technical Writer": "FEDIP Senior Practitioner",
  "Test Engineer": "FEDIP Practitioner",
  "Test Manager": "FEDIP Advanced Practitioner",
  "Tester (Test Engineer)": "FEDIP Associate Practitioner",
  "Trainee Business Analyst": "FEDIP Associate Practitioner",
  "Trainee Business Architect": "FEDIP Associate Practitioner",
  "Trainee Clinical Coder": "FEDIP Associate Practitioner",
  "User Researcher": "FEDIP Practitioner"
};
